pipeline {
	agent any
	stages {
    stage('Terraform Plan') {
      steps {
        script {
          dir('module6/jenkins') {
            // Initialize Terraform
            sh 'terraform init'

            // Run Terraform Plan
            sh 'terraform plan'
          }
        }
      }
    }
	}
}
