pipeline {
	agent any

	stages {
    stage('Terraform Plan') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
            dir('module6/sample') {
              sh '''
                set +x
                terraform init
                terraform plan
              '''
            }
          }
        }
      }
    }
	}
}
